name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: temu_pro
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U dev -d temu_pro"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Postgres
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U dev -d temu_pro; do sleep 1; done
        env:
          PGPASSWORD: dev

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=postgresql://dev:dev@127.0.0.1:5432/temu_pro?schema=public" >> $GITHUB_ENV

      - name: Run Prisma migrations
        run: npx prisma migrate deploy

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Seed test user
        run: npx ts-node prisma/seed-test-user.ts

      - name: Build app
        run: npm run build

      - name: Start app
        run: nohup npm start & sleep 5

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --project=chromium --reporter=list
        env:
          PW_TEST_EMAIL: playwright@test.local
          PW_TEST_PASSWORD: password123

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
